#XPOverhaul Config File
enchanting:
  bottle-enchanting:
    allow-bottle-enchanting: true
    levels-per-bottle: 1
  require-lapis: true
balances:
  initial-balance: 0
  allow-viewing-other-balances: false
  xptop-number: 5
