name: XPOverhaul
main: io.github.dkrolls.XPOverhaul.Main
author: Smileyguy19131/DKrolls
version: 1.0

commands:
  xpdeposit:
    description: Deposits XP into an account.
    aliases: [xpd]
    permission: XPO.transaction
    usage: Correct usage is /xpdeposit [amount](L).
  xpwithdraw:
    description: Withdraws XP from an account.
    aliases: [xpw]
    permission: XPO.transaction
    usage: Correct usage is /xpwithdraw [amount](L).
  xpbalance:
    description: Finds the XP in an account.
    aliases: [xpb]
    permission: XPO.transaction
    usage: Correct usage is /xpbalance (account).
  xpsend:
    description: Transfers XP from one account to another.
    aliases: [xps]
    permission: XPO.send
    usage: Correct usage is /xpsend (source) [destination] [amount].
  xpmodify:
    description: Modifies an account balance. Negative deducts XP.
    aliases: [xpm]
    permission: XPO.admin
    usage: Correct usage is /xpmodify [account] (-)[amount].
  xptop:
    description: Shows top XP balances.
    aliases: [xpt]
    permission: XPO.transaction.top
    usage: Correct usage is /xptop.
  xpreload:
    description: Reloads configuration files.
    aliases: [xpr]
    permission: XPO.admin
    usage: Correct usage is /xpreload.

permissions:
  XPO.transaction:
    description: Allows access to depositing, withdrawing and checking XP balance.
    default: true
    children:
      XPO.transaction.top: true
  XPO.transaction.other:
    description: Allows viewing of others' balances.
    default: op
  XPO.transaction.top:
    description: Allows viewing top XP balances.
    default: true
  XPO.send:
    description: Allows transfer from one account to another.
    default: true
    children:
      XPO.send.other: true
  XPO.send.other:
    description: Allows transferring from a source that is not one's own.
    default: op
  XPO.admin:
    description: Allows modifying balances and reloading config.
    default: op
  XPO.bottle:
    description: Allows bottling of experience using an enchanting table.
    default: true
